#!/bin/sh
cd ~/Light-Guide-MC
cp NewAngeloGeometries/Straight/DetectorConstruction.cc src/.
cp src/G4OpBoundaryProcess.cc.11 src/G4OpBoundaryProcess.cc
make clean; make
OpNovice2 vis.mac > tempoutput_straight_juniper11
grep Photons tempoutput_straight_juniper11
