#!/bin/sh
#
# cmake -Dgeant4_DIR=/Users/brash/Geant4/geant4_install_11.2.1/lib/cmake/Geant4/ .
#
# might have to remove CMakeCache.txt and CMakeFiles/ and re-run cmake
#
export G4FORCENUMBEROFTHREADS=1
cd ~/Light-Guide-MC
cp NewAngeloGeometries/Straight/DetectorConstruction.cc src/.
#cp src/G4OpBoundaryProcess.cc.11 src/G4OpBoundaryProcess.cc
make clean; make
OpNovice2 vis.mac > tempoutput_straight_juniper11
grep Photons tempoutput_straight_juniper11
