#!/bin/sh
#
cd ~/Light-Guide-MC

#
#  Remake from scratch
rm CMakeCache.txt
rm -rf CMakeFiles
cmake -DGeant4_DIR=/Users/brash/Geant4/geant4_install_11.2.1/lib/cmake/Geant4/ .
#
#

# Set the number of threads to 1
export G4FORCENUMBEROFTHREADS=1

# Copy the straight geometry file to the source directory
cp NewAngeloGeometries/Straight/DetectorConstruction.cc src/.
#cp src/G4OpBoundaryProcess.cc.11 src/G4OpBoundaryProcess.cc
make clean; make
./OpNovice2 vis.mac > tempoutput_straight_juniper11
grep Photons tempoutput_straight_juniper11
